frontend:
    image: node:16-alpine3.15
    command: ['npm', 'run', 'dev']
    working_dir: /app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_RFO_BACKEND_URL=${RFO_BACKEND_URL}
      - NEXT_PUBLIC_RFO_STAGE=${RFO_STAGE}
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - ./frontend:/app
      - frontend.node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - proxy-network
      - default
    labels:
      - "traefik.enable=true"
      # Bestimmt das Netzwerk für Traefik (Nur einmal nötig)
      - "traefik.docker.network=proxy-network"
      
      # HTTP Router mit automatischem Redirect auf HTTPS
      - "traefik.http.routers.im-frontend-http.entrypoints=web"
      - "traefik.http.routers.im-frontend-http.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.im-frontend-http.service=im-frontend-service"
      - "traefik.http.routers.im-frontend-http.middlewares=im-frontend-redirect"
      - "traefik.http.middlewares.im-frontend-redirect.redirectscheme.scheme=https"
      
      # HTTPS Router (KORRIGIERT: .service-Zuweisung gefixt)
      - "traefik.http.routers.im-frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.im-frontend-secure.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.im-frontend-secure.service=im-frontend-service"
      - "traefik.http.routers.im-frontend-secure.tls=true"
      - "traefik.http.routers.im-frontend-secure.tls.certresolver=myresolver"
      
      # Interner Next.js Port im Container
      - "traefik.http.services.im-frontend-service.loadbalancer.server.port=3000"