services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: zso_socket_proxy
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - SERVICES=1
    networks:
      proxy-network:
        aliases:
          - socket-proxy

  traefik:
    image: traefik:latest
    container_name: zso_apps_proxy
    restart: unless-stopped
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Zwingt Traefik, Container ohne traefik.enable=true komplett zu ignorieren
      - "--providers.docker.endpoint=tcp://socket-proxy:2375"
      - "--entrypoints.web.address=:${PROXY_HTTP_PORT}"
      - "--entrypoints.websecure.address=:${PROXY_HTTPS_PORT}"
      # Wir aktivieren TLS und den Resolver wieder global auf dem HTTPS-Port, damit Traefik die Hoheit hat:
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/certs/acme.json"
    ports:
      - "${PROXY_HTTP_PORT}:${PROXY_HTTP_PORT}"
      - "${PROXY_HTTPS_PORT}:${PROXY_HTTPS_PORT}"
    volumes:
      - ./certs:/certs
    networks:
      - proxy-network
    depends_on:
      - socket-proxy

networks:
  proxy-network:
    external: true