services:
  postgresql-zskarte:
    ports:
      - "55432:5432"
    environment:
      - POSTGRESQL_PASSWORD=supersecret123
      - POSTGRESQL_DATABASE=zskarte

  pgadmin-zskarte:
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@zskarte.ch
      - PGADMIN_DEFAULT_PASSWORD=zskarte

  server-zskarte:
    ports: !override
      - "${ZSKARTE_API_PORT}:1337"
    environment:
      - DATABASE_HOST=postgresql-zskarte
      - DATABASE_PORT=5432
    env_file:
      - .env
    networks:
      - zskarte
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.zsk-api-http.entrypoints=web"
      - "traefik.http.routers.zsk-api-http.rule=Host(`${ZSKARTE_API_DOMAIN}`) && !PathPrefix(`/admin`)"
      - "traefik.http.routers.zsk-api-http.service=zsk-api-service"
      - "traefik.http.routers.zsk-api-http.middlewares=zsk-api-redirect"
      - "traefik.http.middlewares.zsk-api-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.zsk-api-secure.entrypoints=websecure"
      - "traefik.http.routers.zsk-api-secure.rule=Host(`${ZSKARTE_API_DOMAIN}`) && !PathPrefix(`/admin`)"
      - "traefik.http.routers.zsk-api-secure.tls=true"
      - "traefik.http.routers.zsk-api-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.zsk-api-secure.service=zsk-api-service"
      - "traefik.http.services.zsk-api-service.loadbalancer.server.port=1337"

  app-zskarte:
    ports: !override
      - "${ZSKARTE_MAIN_PORT}:80"
    env_file:
      - .env
    networks:
      - zskarte
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.zsk-app-http.entrypoints=web"
      - "traefik.http.routers.zsk-app-http.rule=Host(`${ZSKARTE_MAIN_DOMAIN}`)"
      - "traefik.http.routers.zsk-app-http.service=zsk-app-service"
      - "traefik.http.routers.zsk-app-http.middlewares=zsk-app-redirect"
      - "traefik.http.middlewares.zsk-app-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.zsk-app-secure.entrypoints=websecure"
      - "traefik.http.routers.zsk-app-secure.rule=Host(`${ZSKARTE_MAIN_DOMAIN}`)"
      - "traefik.http.routers.zsk-app-secure.tls=true"
      - "traefik.http.routers.zsk-app-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.zsk-app-secure.service=zsk-app-service"
      - "traefik.http.services.zsk-app-service.loadbalancer.server.port=80"

networks:
  proxy-network:
    external: true